# Generated by Django 4.2.7 on 2023-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
