# Créer un utilisateur avec la méthode POST
POST http://localhost:8000/commande/create_commande
Content-Type: application/json

{
  "id":"5",  
  "value": "test4"
}

###
GET http://localhost:8000/commande/getAll


###
GET http://localhost:8000/commande/getOne/5

###
GET http://localhost:8000/commande/helloWorld