# Generated by Django 4.2.7 on 2023-12-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0003_remove_commande_commande_id_alter_commande_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='id',
            new_name='commande_id',
        ),
    ]
