# Generated by Django 4.2.7 on 2023-12-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0004_rename_id_commande_commande_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='commande_id',
            new_name='id',
        ),
    ]
